[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
common = {path = "../common"}
tonic = "0.10"
prost = "0.12"
tokio = { version =  "1.0", features = ["full"]}
dashmap = "5.5"
clap = {version = "4.4", features = ["derive"]}